version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1234" # user and passowrd
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
